### ISSUE TITLE
 how it's working?

### ISSUE THREAD

**Issue by marrudagg** [ffpetrozzi/esx_carkey#1]
by adding the key command / givekey MYID PLATE I have it in my inventory but when using it nothing happens, the vehicle is open and no animation is played

**Comment by ffpetrozzi** [comment]
> by adding the key command / givekey MYID PLATE I have it in my inventory but when using it nothing happens, the vehicle is open and no animation is played

Hi, make sure you have correctly entered the strings you find in the readme in the respective files.  If it doesn't work and you have done everything correctly, check if it gives you any errors.
