### ISSUE TITLE
WHAT HAPPEN IF THE ITEM WILL LOST?

### ISSUE THREAD

**Issue by mikel13200** [ffpetrozzi/esx_carkey#2]
WHAT HAPPEN IF THE ITEM WILL LOST? WHAT SHOULD I DO?

**Comment by ffpetrozzi** [comment]
> WHAT HAPPEN IF THE ITEM WILL LOST? WHAT SHOULD I DO?

Hi, you have to create a blip where players can get the key again. I think I'll make an update soon.
